//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Carduiitem_prefab
    {
        public const string BundleName = "carduiitem_prefab";
        public const string CARDUIITEM = "CardUIItem";
    }
    public class Enemyinfopanel_prefab
    {
        public const string BundleName = "enemyinfopanel_prefab";
        public const string ENEMYINFOPANEL = "EnemyInfoPanel";
    }
    public class Game_unity
    {
        public const string BundleName = "game_unity";
        public const string GAME = "Game";
    }
    public class Lubantables
    {
        public const string BundleName = "lubantables";
        public const string CARD_TBCARD = "card_tbcard";
        public const string PLAYER_INFO_TBPLAYERINFO = "player_info_tbplayerinfo";
        public const string SHOP_TBSHOP = "shop_tbshop";
    }
    public class Minionuiitem_prefab
    {
        public const string BundleName = "minionuiitem_prefab";
        public const string MINIONUIITEM = "MinionUIItem";
    }
    public class Playerinfopanel_prefab
    {
        public const string BundleName = "playerinfopanel_prefab";
        public const string PLAYERINFOPANEL = "PlayerInfoPanel";
    }
    public class Shopinfopanel_prefab
    {
        public const string BundleName = "shopinfopanel_prefab";
        public const string SHOPINFOPANEL = "ShopInfoPanel";
    }
}
