//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Animeimagebackground_prefab
    {
        public const string BundleName = "animeimagebackground_prefab";
        public const string ANIMEIMAGEBACKGROUND = "AnimeImageBackGround";
    }
    public class Carduiitem_prefab
    {
        public const string BundleName = "carduiitem_prefab";
        public const string CARDUIITEM = "CardUIItem";
    }
    public class Dragpanel_prefab
    {
        public const string BundleName = "dragpanel_prefab";
        public const string DRAGPANEL = "DragPanel";
    }
    public class Enemyinfopanel_prefab
    {
        public const string BundleName = "enemyinfopanel_prefab";
        public const string ENEMYINFOPANEL = "EnemyInfoPanel";
    }
    public class Game_unity
    {
        public const string BundleName = "game_unity";
        public const string GAME = "Game";
    }
    public class Lubantables
    {
        public const string BundleName = "lubantables";
        public const string TBCARD = "tbcard";
        public const string TBPLAYERINFO = "tbplayerinfo";
        public const string TBSHOP = "tbshop";
        public const string CARD = "Card";
        public const string EQUALITY = "EQuality";
        public const string ITEMEXCHANGE = "ItemExchange";
        public const string PLAYERINFO = "PlayerInfo";
        public const string SHOP = "Shop";
        public const string TABLES = "Tables";
        public const string ACCESSFLAG = "AccessFlag";
        public const string CIRCLE = "Circle";
        public const string RECTANGLE = "Rectangle";
        public const string SHAPE = "Shape";
        public const string TESTEXCELBEAN1 = "TestExcelBean1";
        public const string TESTEXCELBEAN2 = "TestExcelBean2";
        public const string VECTOR2 = "vector2";
        public const string VECTOR3 = "vector3";
        public const string VECTOR4 = "vector4";
    }
    public class Minionuiitem_prefab
    {
        public const string BundleName = "minionuiitem_prefab";
        public const string MINIONUIITEM = "MinionUIItem";
    }
    public class Playerinfopanel_prefab
    {
        public const string BundleName = "playerinfopanel_prefab";
        public const string PLAYERINFOPANEL = "PlayerInfoPanel";
    }
    public class Shopinfopanel_prefab
    {
        public const string BundleName = "shopinfopanel_prefab";
        public const string SHOPINFOPANEL = "ShopInfoPanel";
    }
}
