
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.player_info
{
public partial class TbPlayerInfo
{
    private readonly System.Collections.Generic.Dictionary<int, PlayerInfo> _dataMap;
    private readonly System.Collections.Generic.List<PlayerInfo> _dataList;
    
    public TbPlayerInfo(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayerInfo>();
        _dataList = new System.Collections.Generic.List<PlayerInfo>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PlayerInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PlayerInfo.DeserializePlayerInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PlayerInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<PlayerInfo> DataList => _dataList;

    public PlayerInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlayerInfo Get(int key) => _dataMap[key];
    public PlayerInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

