
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Shop : Luban.BeanBase
{
    public Shop(JSONNode _buf) 
    {
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { if(!_buf["upgrade_cost"].IsNumber) { throw new SerializationException(); }  UpgradeCost = _buf["upgrade_cost"]; }
        { if(!_buf["refresh_cost"].IsNumber) { throw new SerializationException(); }  RefreshCost = _buf["refresh_cost"]; }
    }

    public static Shop DeserializeShop(JSONNode _buf)
    {
        return new Shop(_buf);
    }

    /// <summary>
    /// 星级
    /// </summary>
    public readonly int Star;
    /// <summary>
    /// 升级费用<br/>-1代表无法升级
    /// </summary>
    public readonly int UpgradeCost;
    /// <summary>
    /// 刷新所需费用
    /// </summary>
    public readonly int RefreshCost;
   
    public const int __ID__ = 2576150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "star:" + Star + ","
        + "upgradeCost:" + UpgradeCost + ","
        + "refreshCost:" + RefreshCost + ","
        + "}";
    }
}

}

