
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public card.TbCard TbCard {get; }
    public player_info.TbPlayerInfo TbPlayerInfo {get; }
    public shop.TbShop TbShop {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCard = new card.TbCard(loader("card_tbcard"));
        TbPlayerInfo = new player_info.TbPlayerInfo(loader("player_info_tbplayerinfo"));
        TbShop = new shop.TbShop(loader("shop_tbshop"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCard.ResolveRef(this);
        TbPlayerInfo.ResolveRef(this);
        TbShop.ResolveRef(this);
    }
}

}
